### ISSUE TITLE
Add padding to .learnSomething (or the children containing text)

### ISSUE THREAD

**Issue by h3xar0n** [amtabug/Cocolmar#1]
The layout is fantastic, and with this one exception, you met the design perfectly. We may want to give some breathing room to the text in this section when we shrink the width:

![padding](https://user-images.githubusercontent.com/21048592/39216446-9014b04e-47d0-11e8-8b4d-81e44a31f959.PNG)

Try adding some padding to this class, or, if you think it will look better, specifically target the child containers to add padding deeper inside:

https://github.com/amtabug/Cocolmar/blob/a3b12d8574516c422e072c68f1a5b17df2db9398/resources/css/style.css#L80-L84

**Comment by amtabug** [comment]
Done, thank you.
