### ISSUE TITLE
Semantic HTML

### ISSUE THREAD

**Issue by h3xar0n** [amtabug/Cocolmar#3]
Overall you made good use of semantic HTML tags. How do you think you can incorporate `<section>` and `<button>` to be more specific than `<div>` for these cases?

https://github.com/amtabug/Cocolmar/blob/a3b12d8574516c422e072c68f1a5b17df2db9398/index.html#L48

https://github.com/amtabug/Cocolmar/blob/a3b12d8574516c422e072c68f1a5b17df2db9398/index.html#L55-L57

https://github.com/amtabug/Cocolmar/blob/a3b12d8574516c422e072c68f1a5b17df2db9398/index.html#L61

https://github.com/amtabug/Cocolmar/blob/a3b12d8574516c422e072c68f1a5b17df2db9398/index.html#L78

Some resources to consider:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by amtabug** [comment]
Corrected, thank you.
