### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by h3xar0n** [amtabug/Cocolmar#4]
Grade: **Exceeds Expectations**

Overall, this was an excellent project. The site is responsive, matches the spec well, and just as importantly, the code was well-written and tidy.

Using a few more semantic tags would be good practice, although, for the most part, the HTML used them well. 

It would be great to see the project once the padding has been added. Excellent work!

**Comment by amtabug** [comment]
Thank you for the tips and for reviewing.
